server:
  port: 5000
spring:
  application:
    name: atguigu-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.0.107
    password: 123321cc..
    database: 14
    port: 6381
  session:
    store-type: redis
  cloud:
    nacos:
      server-addr: localhost:8848
    alicloud:
      access-key: 123456
      secret-key: 123456
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
custom:
  oss:
    bucketName: 123456
    urlPrefix: https://
    urlSuffix: oss-cn-beijing.aliyuncs.com
